### ISSUE TITLE
Support Host Network Mode for Pods? 

### ISSUE THREAD

**Issue by qchenzi** [zilliztech/milvus-operator#134]
## Description
Milvus is often used for real-time data processing and large-scale vector similarity search, which require high throughput and low latency. Supporting host network mode at the Pod level can reduce network latency by eliminating container networking overhead, crucial for performance-sensitive applications.

## Proposed Solution
Introduce an option in the Milvus Operator configuration to enable host network mode for specific components, **such as the milvus-proxy**, allowing users to opt-in based on their performance needs.

## Benefits
**Reduced Latency**: Direct access to the host's network stack can significantly lower network latency.
**Improved Throughput**: Enhanced network performance can increase query handling capacity.
**Flexibility**: Users can optimize deployments based on specific requirements.

Supporting host network mode for specific components would greatly benefit real-time data processing applications in Milvus.

Thank you for considering this request.

**Comment by haorenfsa** [comment]
Looks good to me. @qchenzi Would you prefer to add it by yourself?

**Comment by qchenzi** [comment]
Sure, I can try to add it myself. But I'm not entirely clear on the related logic and where to start. Could you please provide some guidance or suggestions, particularly on which part of the Milvus Operator configuration I should focus on and any specific components or files that are critical for implementing the host network mode? Your help would be greatly appreciated. Thank you!

**Comment by haorenfsa** [comment]
If I understand the feature correctly. We should add fields in `Milvus CR` to adjust the `spec.hostNetwork` & `spec.dnsPolicy` in Pod Template. The final pod manifest should be look like below:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
```

First we need add `hostNetwork` & `dnsPolicy`  fields in `ComponentSpec` struct located in https://github.com/zilliztech/milvus-operator/blob/592de3d6e6f7b7a43fbd11c5f2e99d211b036767/apis/milvus.io/v1beta1/components_types.go#L33
And use `generate-all` to update the CRD manifests & the structs' deep copy functions.

By doing these, we actually add configuration fields like the 2 cases below:

```yaml
# Case 1: configure all components to hostnetwork
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: my-release
  labels:
    app: milvus
spec:
  components:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
```
```yaml
# Case 2: configure some of the components to hostnetwork
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: my-release
  labels:
    app: milvus
spec:
  components:
    proxy:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
    mixcoord:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
```

Then we shall add render logics to add these fields in deploy.spec.podTemplate in https://github.com/zilliztech/milvus-operator/blob/592de3d6e6f7b7a43fbd11c5f2e99d211b036767/pkg/controllers/deployment_updater.go#L80

Then it's also required to add unittests in https://github.com/zilliztech/milvus-operator/blob/main/pkg/controllers/deployment_updater_test.go to verify the render logics works.
