### ISSUE TITLE
milvus operator is difficult to install as a dependent chart due to the inconsistent use of `release.Name` and `release.FullName`

### ISSUE THREAD

**Issue by butler54** [zilliztech/milvus-operator#135]
I wanted to install milvus for various reasons as a dependent chart e.g.

```
milvus/
milvus/Chart.yaml
milvus/values.yaml
```

where: `Chart.yaml`
```yaml
apiVersion: v2
name: milvus
description: A Helm chart deploying milvus via the operator

type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
- name: milvus-operator
  version: "0.9.16"
  repository: "https://zilliztech.github.io/milvus-operator/"
```

values.yaml
```yaml

```

is empty.

The problem is `Release.fullName` becomes `milvus-milvus-operator` and `release.Name` becomes `milvus`.

This results in inconsistencies around the Certificate generated. The only way to make this work is to set the following in `values.yaml`

```
milvus-operator:
  fullnameOverride: "milvus"
```
