### ISSUE TITLE
v2.3.3 upgrade to v2.4.6 failed.

### ISSUE THREAD

**Issue by erigo** [zilliztech/milvus-operator#167]
Follow the offical doc: https://milvus.io/docs/upgrade_milvus_cluster-operator.md to upgrade my milvus cluster.

copy the yaml to apply.
```
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: my-release
spec:
  components:
    enableRollingUpdate: true
    imageUpdateMode: rollingUpgrade # Default value, can be omitted
    image: milvusdb/milvus:v2.4.8
```
modify the name and image feild as my cluster and docker register.

`kubelet apply -f milvusupgrade.yaml`

Then my cluster crashed... T.T

Maybe some default config change to standalone. here is the pod error:
<img width="1051" alt="image" src="https://github.com/user-attachments/assets/9f813c97-0a2c-408b-a88c-9a3229930995">

SOS!!!

**Comment by erigo** [comment]
my cluster yaml is :milvus_cluster_minimum.yaml
```
# This is a sample to deploy a milvus cluster using pulsar with minimum cost of resources.
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: snrobots
  labels:
    app: milvus
spec:
  mode: cluster
  components:
    proxy:
      serviceType: NodePort
  dependencies:
    etcd:
      inCluster:
        values:
          replicaCount: 1
    pulsar:
      inCluster:
        values:
          components: 
            autorecovery: false
            functions: false
            toolset: false
            pulsar_manager: false
          monitoring:
            prometheus: false
            grafana: false
            node_exporter: false
            alert_manager: false
          proxy:
            replicaCount: 1
            resources:
              requests:
                cpu: 0.01
                memory: 256Mi
            configData:
              PULSAR_MEM: >
                -Xms256m -Xmx256m
              PULSAR_GC: >
                -XX:MaxDirectMemorySize=256m
          bookkeeper:
            replicaCount: 2
            resources:
              requests:
                cpu: 0.01
                memory: 256Mi
            configData:
              PULSAR_MEM: >
                -Xms256m
                -Xmx256m
                -XX:MaxDirectMemorySize=256m
              PULSAR_GC: >
                -Dio.netty.leakDetectionLevel=disabled
                -Dio.netty.recycler.linkCapacity=1024
                -XX:+UseG1GC -XX:MaxGCPauseMillis=10
                -XX:+ParallelRefProcEnabled
                -XX:+UnlockExperimentalVMOptions
                -XX:+DoEscapeAnalysis
                -XX:ParallelGCThreads=32
                -XX:ConcGCThreads=32
                -XX:G1NewSizePercent=50
                -XX:+DisableExplicitGC
                -XX:-ResizePLAB
                -XX:+ExitOnOutOfMemoryError
                -XX:+PerfDisableSharedMem
                -XX:+PrintGCDetails
          zookeeper:
            replicaCount: 1
            resources:
              requests:
                cpu: 0.01
                memory: 256Mi
            configData:
              PULSAR_MEM: >
                -Xms256m
                -Xmx256m
              PULSAR_GC: >
                -Dcom.sun.management.jmxremote
                -Djute.maxbuffer=10485760
                -XX:+ParallelRefProcEnabled
                -XX:+UnlockExperimentalVMOptions
                -XX:+DoEscapeAnalysis -XX:+DisableExplicitGC
                -XX:+PerfDisableSharedMem
                -Dzookeeper.forceSync=no
          broker:
            replicaCount: 1
            resources:
              requests:
                cpu: 0.01
                memory: 256Mi
            configData:
              PULSAR_MEM: >
                -Xms256m
                -Xmx256m
              PULSAR_GC: >
                -XX:MaxDirectMemorySize=256m
                -Dio.netty.leakDetectionLevel=disabled
                -Dio.netty.recycler.linkCapacity=1024
                -XX:+ParallelRefProcEnabled
                -XX:+UnlockExperimentalVMOptions
                -XX:+DoEscapeAnalysis
                -XX:ParallelGCThreads=32
                -XX:ConcGCThreads=32
                -XX:G1NewSizePercent=50
                -XX:+DisableExplicitGC
                -XX:-ResizePLAB
                -XX:+ExitOnOutOfMemoryError
    storage:
      inCluster:
        values:
          mode: standalone
  config:
    milvus:
      log:
        level: info
    component:
      proxy:
        timeTickInterval: 150
```

upgrade yaml:
```
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: snrobots
spec:
  components:
    enableRollingUpdate: true
    imageUpdateMode: all # Default value, can be omitted
    image: registry.cn-hangzhou.aliyuncs.com/zilliztech/milvus:v2.4.6
```
