### ISSUE TITLE
custom kafka ssl cert

### ISSUE THREAD

**Issue by artesby** [zilliztech/milvus-operator#199]
does operator support specifying path to custom ssl certificate for kafka access? i am facing error

```
2024/10/17 13:32:23 checkKafka with backoff failed, retry 1, err: check consume offset from broker failed: error dialing all brokers, one of the errors: failed to dial: tls: failed to verify certificate: x509: certificate signed by unknown authority
```

tried this without success:

```
config:
    kafka:
      securityProtocol: SASL_SSL
      saslMechanisms: SCRAM-SHA-512
      tlsCaCert: <path-to-cert>
```
