### ISSUE TITLE
[Feature] Ability to set annotations for checker job

### ISSUE THREAD

**Issue by aceat64** [zilliztech/milvus-operator#20]
Currently it does not seem possible to set annotations on just the checker job. I need this in order to add some annotations used by ArgoCD.

Without being able to set these annotations, ArgoCD views the job as "missing" once the has completed and the `ttlSecondsAfterFinished` has expired. It then re-creates the job, resulting in new jobs being run every few minutes.

**Comment by gruberdev** [comment]
You can use `helmCharts:` with `Kustomize` in order to do that, while that is not added to the main branch:

`app/base/kustomization.yaml`

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: milvus-operator
  includeCRDs: true
  valuesInline:
    image:
      repository: milvusdb/milvus-operator
      pullPolicy: IfNotPresent
      tag: "v0.8.1"
    # {...}
    # The rest of your values here
  releaseName: milvus-operator
  version: 0.8.1
  repo: https://zilliztech.github.io/milvus-operator/
```


`app/overlay/milvus-job.yaml`

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    helm.sh/chart: milvus-operator-0.8.1
    app.kubernetes.io/name: milvus-operator
    app.kubernetes.io/instance: milvus-operator
    app.kubernetes.io/version: "0.8.1"
    app.kubernetes.io/managed-by: Helm
  name: "milvus-operator-checker"
  namespace: "milvus-operator"
spec:
  ttlSecondsAfterFinished: 100
````


`app/kustomization.yaml`
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./base
patchesStrategicMerge:
- overlay/milvus-job.yaml
patchesJson6902:
  - target:
      group: batch
      version: v1
      kind: Job
      name: milvus-operator-checker
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1hook
        value: PostSync
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1hook-delete-policy
        value: HookSucceeded
```


`app.yaml`
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: milvus-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: 'https://github.com/{your git}'
    path: {your base kustomize.yaml path}
    targetRevision: main
  destination:
    namespace: milvus-operator
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - Prune=true
    - ServerSideApply=true
  retry:
    limit: 5
    backoff:
      duration: 20s
      factor: 2
      maxDuration: 15m
```

I did a similar setup [here](https://github.com/gruberdev/homelab/tree/main/apps/services/mlops/milvus) and [here](https://github.com/gruberdev/homelab/blob/main/apps/argocd/base/mlops/milvus.yaml).

How it'd look like at the end:
```md
app/
├── base/
│   └── kustomization.yaml  # Helm chart settings
├── overlay/
│   └── milvus-job.yaml    # Job specs
├── kustomization.yaml     # Merges all the things
└── app.yaml               # ArgoCD app specs
```

Just make sure you've enabled Helm support in ArgoCD by setting [--enable-helm to true. This ensures that ArgoCD understands the Helm-related directives in your Kustomization](https://github.com/argoproj/argo-cd/issues/7835#issuecomment-985902350).
