### ISSUE TITLE
nodeSelector not work for Component

### ISSUE THREAD

**Issue by lysShub** [zilliztech/milvus-operator#21]
nodeSelector not work for Components, e.g milvus-etcd

```yaml
# This is a sample to deploy a standalone milvus in milvus-operator's default configurations.
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: my-milvus
spec:
  components:
    nodeSelector: 
      beta.kubernetes.io/arch: amd64 
```
