### ISSUE TITLE
Issue with setting rocksmq settings through config

### ISSUE THREAD

**Issue by nairan-deshaw** [zilliztech/milvus-operator#218]
I have the below operator config:
```
  config:
    common:
      security:
        authorizationEnabled: true
    proxy:
      accessLog:
        enable: true
      maxUserNum: 500
      maxRoleNum: 100
    rocksmq:
      retentionTimeInMinutes: 10
      retentionSizeInMB: 2048
      compactionInterval: 600
```

However, the rocksmq config is always set to an empty dict in the configmap that is created:

```
Data                                                                 
====                                                                 
user.yaml:                                                           
----                                                                 
common:                                                              
  security:                                                          
    authorizationEnabled: true                                       
dataCoord:                                                           
  enableActiveStandby: true                                          
etcd:                                                                
  endpoints:                                                         
  - <blah>
  rootPath: operator                                                 
indexCoord:                                                          
  enableActiveStandby: true                                          
messageQueue: rocksmq                                                
minio:                                                               
  accessKeyID: minioadmin                                            
  address: <blah>                   
  bucketName: operator                                               
  port: 9000                                                         
  secretAccessKey: minioadmin                                        
mq:                                                                  
  type: rocksmq                                                      
msgChannel:                                                          
  chanNamePrefix:                                                    
    cluster: operator                                                
proxy:                                                               
  accessLog:                                                         
    enable: true                                                     
  maxRoleNum: 100                                                    
  maxUserNum: 500                                                    
queryCoord:                                                          
  enableActiveStandby: true                                          
rocksmq: {}                                                          
rootCoord:                                                           
  enableActiveStandby: true                                          
```

From my understanding, Milvus uses this as to populate the user.yaml file which is eventually picked by Milvus. Other configs seem to be populated fine. Is there something missing or wrong here?

Thanks.
