### ISSUE TITLE
I can't set the loadBalancerIP using the milvus-operator

### ISSUE THREAD

**Issue by iurii-stepanov** [zilliztech/milvus-operator#224]
I need to set a static ip address for the LoadBalancer. I am using the annotations for my cloud provider for creating a LoadBalancer:
```
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
spec:
  mode: cluster
  components:
    proxy:
      replicas: 1
      serviceAnnotations:
        provider.cloud/load-balancer-type: internal
        provider.cloud/subnet-id: e2l5v7pklni9pesf30b1 # vpc-region-ru-central1-b-subnet
      serviceType: LoadBalancer
```
but I cannot set the parameter `loadBalancerIP`.
I've tried to do this, but it doesn't work:
```
  config:
    service:
      loadBalancerIP: 10.97.148.30
```
Please tell me how I can set loadBalancerIP?
