### ISSUE TITLE
I can't control RollingUpdate strategy for QueryNode using milvus-operator

### ISSUE THREAD

**Issue by iurii-stepanov** [zilliztech/milvus-operator#225]
How can I manage the RollingUpdate strategy for QueryNodes using milvus-operator?
By default:
```
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
```
How i can change it to 
```
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
```
The fact is that there is no free memory in the cluster to deploy another QueryNode during the update.
