### ISSUE TITLE
milvus-operator does not make any real changes when deleting a pod annotation

### ISSUE THREAD

**Issue by iurii-stepanov** [zilliztech/milvus-operator#232]
milvus-operator version 1.1.4

If I add the annotation to the CRD and and apply the changes, then the changes are applied.
```
spec:
  components:
    queryNode:
      podAnnotations:
        some-annotation: some-value
```

But if I delete the annotation and apply the changes, then the operator does not respond to these changes and they are not applied.
```
spec:
  components:
    queryNode:
      # podAnnotations:
      #   some-annotation: some-value
```

Expected: when you delete an annotation, the changes are applied.
