### ISSUE TITLE
spec.dependencies.etcd.endpoints in body must be of type array

### ISSUE THREAD

**Issue by welyss** [zilliztech/milvus-operator#273]
error msg in operator logs:

> {"level":"error","ts":"2025-02-25T08:32:43Z","msg":"Reconciler error","controller":"milvus","controllerGroup":"milvus.io","controllerKind":"Milvus","Milvus":{"name":"dev-release","namespace":"milvus"},"namespace":"milvus","name":"dev-release","reconcileID":"ecaeb1bc-396b-4cd9-a891-a10bda8e6f93","error":"Milvus.milvus.io \"dev-release\" is invalid: spec.dependencies.etcd.endpoints: Invalid value: \"null\": spec.dependencies.etcd.endpoints in body must be of type array: \"null\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.6/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.6/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.6/pkg/internal/controller/controller.go:227"}

operator version is:
```
[root@localhost milvus]# kubectl describe pod -n milvus-operator|grep 'Image:'
    Image:         milvusdb/milvus-operator:v1.2.1
```

milvus cluster etcd section yaml:
```
...
  dependencies:
    etcd:
      inCluster:
        values:
          autoCompactionMode: revision
          autoCompactionRetention: "1000"
          extraEnvVars:
          - name: ETCD_QUOTA_BACKEND_BYTES
            value: "4294967296"
          - name: ETCD_HEARTBEAT_INTERVAL
            value: "500"
          - name: ETCD_ELECTION_TIMEOUT
            value: "25000"
          - name: ETCD_SNAPSHOT_COUNT
            value: "10000"
          - name: ETCD_ENABLE_PPROF
            value: "true"
          persistence:
            accessMode: ReadWriteOnce
            enabled: true
            size: 10Gi   #SSD Required
            storageClass: "dba"
          replicaCount: 3
          resources:
            limits:
              cpu: 0.5
              memory: 512Mi
            requests:
              cpu: 0.5
              memory: 512Mi
    msgStreamType: kafka
...
```

k8s version:
```
[root@localhost milvus]# kubectl version --short 
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.24.2
Kustomize Version: v4.5.4
Server Version: v1.18.20
WARNING: version difference between client (1.24) and server (1.18) exceeds the supported minor version skew of +/-1
```
