### ISSUE TITLE
Standalone component appears in stopped state after deploying Milvus in cluster mode using Operator

### ISSUE THREAD

**Issue by opsxlab** [zilliztech/milvus-operator#274]
milvus in cluster mode was created using operator, and after Deployment, the standalone component appears in Deployment and is stopped.
I don't think this is right, there shouldn't be standalone related components.

![Image](https://github.com/user-attachments/assets/7d80fc89-ed5b-410d-ab64-4b6b8f236e7e)

我使用的yaml文件如下
```yaml
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: milvus-release-1
  labels:
    app: milvus
spec:
  mode: cluster
  config: {}
  components:
    image: registry.opsxlab.cn:8443/milvusdb/milvus:v2.5.4
  dependencies:
    etcd:
      inCluster:
        deletionPolicy: Delete
        pvcDeletion: true
        values:
          global:
            imageRegistry: registry.opsxlab.cn:8443
    storage:
      inCluster:
        deletionPolicy: Delete
        pvcDeletion: true
        values:
          image:
            repository: registry.opsxlab.cn:8443/milvusdb/minio
            tag: RELEASE.2023-03-20T20-16-18Z
    pulsar:
      inCluster:
        chartVersion: pulsar-v3
        deletionPolicy: Delete
        pvcDeletion: true
        values:
          pulsar_metadata:
            image:
              repository: registry.opsxlab.cn:8443/apachepulsar/pulsar
              tag: 3.0.7
          images:
            zookeeper:
              repository: registry.opsxlab.cn:8443/apachepulsar/pulsar
              tag: 3.0.7
            proxy:
              repository: registry.opsxlab.cn:8443/apachepulsar/pulsar
              tag: 3.0.7
            broker:
              repository: registry.opsxlab.cn:8443/apachepulsar/pulsar
              tag: 3.0.7
            bookie:
              repository: registry.opsxlab.cn:8443/apachepulsar/pulsar
              tag: 3.0.7
            autorecovery:
              repository: registry.opsxlab.cn:8443/apachepulsar/pulsar
              tag: 3.0.7

```
