### ISSUE TITLE
Milvus Cluster - Query Node Stuck Updating

### ISSUE THREAD

**Issue by linusfr** [zilliztech/milvus-operator#275]
Hey there, I am deploying a Milvus Cluster to Kubernetes using the Helm Chart.

The resource looks like this:

```
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  labels:
    app: milvus-cluster
  name: milvus-cluster
spec:
  components:
    proxy:
      serviceAnnotations:
        external-dns.alpha.kubernetes.io/hostname: <redacted>
      serviceType: LoadBalancer
    queryNode:
      replicas: 6
    volumeMounts:
      - mountPath: /certs
        name: certs
        readOnly: true
    volumes:
      - name: certs
        secret:
          secretName: milvus-cluster-tls
  config:
    common:
      security:
        authorizationEnabled: true
        tlsMode: 1
    minio:
      bucketName: milvus
      region: FRA1
      rootPath: milvus/milvus-cluster
      useSSL: true
    proxy:
      http:
        port: 8080
    tls:
      serverKeyPath: /certs/tls.key
      serverPemPath: /certs/tls.crt
  dependencies:
    storage:
      endpoint: objectstore.fra1.civo.com:443
      external: true
      secretRef: s3-credentials
      type: S3
  mode: cluster
```

The Resource is healthy but not updated:
```
→ kubectl get milvus -n milvus-cluster                                                                                                                                                                                 
NAME             MODE      STATUS    UPDATED   AGE
milvus-cluster   cluster   Healthy   False     23d
```

But the operator keeps on moving the pods of the querynode between two deployments.
This is neverending, it just juggles them forth and back. 
You can see in the following command really well, how every querynode pod gets rotated about a minute apart from each other.

```
→ kubectl get pods -n milvus-cluster --sort-by="{.metadata.creationTimestamp}"   
NAME                                                 READY   STATUS      RESTARTS      AGE
milvus-cluster-etcd-0                                1/1     Running     0             23d
milvus-cluster-etcd-1                                1/1     Running     0             23d
milvus-cluster-etcd-2                                1/1     Running     1 (23d ago)   23d
milvus-cluster-pulsar-pulsar-init-q7xs7              0/1     Completed   0             23d
milvus-cluster-pulsar-zookeeper-1                    1/1     Running     0             23d
milvus-cluster-pulsar-zookeeper-0                    1/1     Running     0             23d
milvus-cluster-pulsar-zookeeper-2                    1/1     Running     0             23d
milvus-cluster-pulsar-recovery-0                     1/1     Running     1 (23d ago)   23d
milvus-cluster-pulsar-bookie-2                       1/1     Running     0             23d
milvus-cluster-pulsar-proxy-1                        1/1     Running     0             23d
milvus-cluster-pulsar-proxy-0                        1/1     Running     0             23d
milvus-cluster-pulsar-broker-1                       1/1     Running     0             23d
milvus-cluster-pulsar-broker-0                       1/1     Running     0             23d
milvus-cluster-pulsar-bookie-init-gpm4d              0/1     Completed   0             23d
milvus-cluster-pulsar-bookie-0                       1/1     Running     0             23d
milvus-cluster-pulsar-bookie-1                       1/1     Running     0             23d
milvus-cluster-milvus-proxy-55c9f8b48c-qxtxk         1/1     Running     0             11d
milvus-cluster-milvus-mixcoord-9675b97c8-5fkzf       1/1     Running     0             11d
milvus-cluster-milvus-indexnode-848dd5d756-rmg8n     1/1     Running     0             11d
milvus-cluster-milvus-datanode-6b5b797b4d-klfg9      1/1     Running     0             11d
milvus-cluster-milvus-querynode-0-7cff7fc4fc-2jgnn   1/1     Running     0             10m
milvus-cluster-milvus-querynode-0-7cff7fc4fc-6wzm6   1/1     Running     0             7m13s
milvus-cluster-milvus-querynode-1-567ff65fcb-9k9f4   1/1     Running     0             4m11s
milvus-cluster-milvus-querynode-1-567ff65fcb-9mgnj   1/1     Running     0             3m11s
milvus-cluster-milvus-querynode-1-567ff65fcb-nd5jx   1/1     Running     0             2m10s
milvus-cluster-milvus-querynode-1-567ff65fcb-7nkhv   1/1     Running     0             70s
milvus-cluster-milvus-querynode-1-567ff65fcb-fqrlj   0/1     Running     0             9s
```

Also in the attachment you can find all the logs for 120 seconds. This should cover the reason for this, but I can't find anything that would cause this.

[logs.txt](https://github.com/user-attachments/files/18961727/logs.txt)

I would appreciate any help :) 
We want to run milvus in production soon but need to resolve this first.

Thanks a bunch in advance,
Linus
