### ISSUE TITLE
How Can I use a custom storageclass for pulsar?

### ISSUE THREAD

**Issue by opsxlab** [zilliztech/milvus-operator#276]
Hi, I'm trying to create a milvus cluster via milvus-operator in a private environment. In our environment, we must specify the storageClassName。

For etcd and minio, I found it's easy to specify the storageclass.

But for pulsar，I added the `spec.dependencies.pulsar.inCluster.values.default_storage.existingStorageClassName` but seems it does not work.

The yaml like this:

```yaml
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: milvus-release-v25
  labels:
    app: milvus
spec:
  mode: cluster
  config: {}
  components:
    image: registry.opsxlab.cn:8443/milvusdb/milvus:v2.5.4
    resources:
      limits:
        cpu: 2
        memory: 8Gi
  dependencies:
    etcd:
      inCluster:
        deletionPolicy: Delete
        pvcDeletion: true
        values:
          global:
            imageRegistry: registry.opsxlab.cn:8443
            storageClass: nfs-sc
    storage:
      inCluster:
        deletionPolicy: Delete
        pvcDeletion: true
        values:
          image:
            repository: registry.opsxlab.cn:8443/milvusdb/minio
            tag: RELEASE.2023-03-20T20-16-18Z
          persistence:
            storageClass: nfs-sc
            accessMode: ReadWriteOnce
            size: 10Gi
    pulsar:
      inCluster:
        chartVersion: pulsar-v3
        deletionPolicy: Delete
        pvcDeletion: true
        values:
          default_storage:
            existingStorageClassName: nfs-sc
          pulsar_metadata:
            image:
              repository: registry.opsxlab.cn:8443/apachepulsar/pulsar
              tag: 3.0.7
          images:
            zookeeper:
              repository: registry.opsxlab.cn:8443/apachepulsar/pulsar
              tag: 3.0.7
            proxy:
              repository: registry.opsxlab.cn:8443/apachepulsar/pulsar
              tag: 3.0.7
            broker:
              repository: registry.opsxlab.cn:8443/apachepulsar/pulsar
              tag: 3.0.7
            bookie:
              repository: registry.opsxlab.cn:8443/apachepulsar/pulsar
              tag: 3.0.7
            autorecovery:
              repository: registry.opsxlab.cn:8443/apachepulsar/pulsar
              tag: 3.0.7
```

![Image](https://github.com/user-attachments/assets/684a8f43-2392-4581-8854-48efa6bee7bb)
