### ISSUE TITLE
unknown field "endpoints" in io.milvus.v1beta1.Milvus.spec.dependencies.pulsar

### ISSUE THREAD

**Issue by welyss** [zilliztech/milvus-operator#285]
doc: [https://github.com/zilliztech/milvus-operator/blob/main/docs/CRD/milvus.md](url)
```
spec:
  # ... Skipped fields
  dependencies: # Optional
    pulsar: # Optional
      # Whether (=true) to use an existed external pulsar as specified in the field endpoints or 
      # (=false) create a new pulsar inside the same kubernetes cluster for milvus.
      external: false # Optional default=false
      # The external pulsar endpoints if external=true
      endpoints:
      - 192.168.1.1:6650
      # in-Cluster pulsar configuration if external=false
      inCluster: 
        # deletionPolicy of pulsar when the milvus cluster is deleted
        deletionPolicy: Retain # Optional ("Delete", "Retain") default="Retain"
        # When deletionPolicy="Delete" whether the PersistantVolumeClaim shoud be deleted when the pulsar is deleted
        pvcDeletion: false # Optional default=false
        # ... Skipped fields
    # ... Skipped fields
```
version: milvus-operator:v1.2.1
i tried "endpoint: xxxx:6650", works, doc wrong or bug
