### ISSUE TITLE
Add etcd metrics monitoring to PodMonitor

### ISSUE THREAD

**Issue by SuperQ** [zilliztech/milvus-operator#310]
When running with a built-in etcd cluster there are currently no metrics.

Add the etcd `client` port to the `PodMonitor` to include metrics from etcd itself.

**Comment by haorenfsa** [comment]
Hi @SuperQ , I just realized that we could use the built-in podmonitor in etcd's helm chart

```yaml
spec:
  dependencies:
    etcd:
      inCluster:
        values:
          metrics:
            ## @param metrics.enabled Expose etcd metrics
            ##
            enabled: false
            ## @param metrics.podAnnotations [object] Annotations for the Prometheus metrics on etcd pods
            ##
            podAnnotations:
              prometheus.io/scrape: "true"
              prometheus.io/port: "2379"
            ## Prometheus Service Monitor
            ## ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#endpoint
            ##
            podMonitor:
              ## @param metrics.podMonitor.enabled Create PodMonitor Resource for scraping metrics using PrometheusOperator
              ##
              enabled: false
```

for more configurable values, check https://artifacthub.io/packages/helm/bitnami/etcd/6.3.3

**Comment by SuperQ** [comment]
Hmm, that's one option. However with this option we need to make sure that the etcd helm chart labeling matches the other PodMonitor labels. Otherwise building dashboards and alerts could be difficult due to missmatch labels between the two.

Unrelated, we're having very bad problems with the etcd helm chart reconcile. It seems very fragile and wedges our operations. We've had several cases where we've had to delete the whole cluster because the helm reconcile doesn't work.

**Comment by haorenfsa** [comment]
@SuperQ I get it. Could you also add a flag field to enable/disable? So that user could decide whether to use helm chart built-in.

**Comment by SuperQ** [comment]
I'm not sure that's a really useful option. I'd prefer a simple batteries-included approach by having the operator directly control the PodMonitor.

**Comment by haorenfsa** [comment]
@SuperQ  What do you think checking the inCluster helm values to decide? Otherwise existing etcds may have multiple podmonitor & scraping jobs.

```
spec:
  dependencies:
    etcd:
      inCluster:
        values:
          metrics:
            podMonitor:
              enabled: false
```
