### ISSUE TITLE
etcd cannot start up

### ISSUE THREAD

**Issue by 804e** [zilliztech/milvus-operator#323]
etcd cannot start properly in my k8s cluster 
etcd config
```yaml
  dependencies:
    etcd:
      inCluster:
        values:
          clusterDomain: itk8s.local
          autoCompactionMode: revision
          autoCompactionRetention: "1000"
          extraEnvVars:
          - name: ETCD_QUOTA_BACKEND_BYTES
            value: "4294967296"
          - name: ETCD_HEARTBEAT_INTERVAL
            value: "500"
          - name: ETCD_ELECTION_TIMEOUT
            value: "25000"
          - name: ETCD_SNAPSHOT_COUNT
            value: "10000"
          - name: ETCD_ENABLE_PPROF
            value: "true"
          persistence:
            accessMode: ReadWriteOnce
            enabled: true
            size: 20Gi   #SSD Required
            storageClass: "milvus-data-storage"
          replicaCount: 3
          resources:
            limits:
              cpu: 1
              memory: 4Gi
            requests:
              cpu: 500m
              memory: 4Gi
```
etcd pod log
```
etcd 10:25:07.50 
etcd 10:25:07.50 Welcome to the Bitnami etcd container
etcd 10:25:07.51 Subscribe to project updates by watching https://github.com/bitnami/containers
etcd 10:25:07.51 Submit issues and feature requests at https://github.com/bitnami/containers/issues
etcd 10:25:07.51 
etcd 10:25:07.51 INFO  ==> ** Starting etcd setup **
etcd 10:25:07.55 INFO  ==> Validating settings in ETCD_* env vars..
etcd 10:25:07.55 WARN  ==> You set the environment variable ALLOW_NONE_AUTHENTICATION=yes. For safety reasons, do not use this flag in a production environment.
etcd 10:25:07.55 INFO  ==> Initializing etcd
etcd 10:25:07.56 INFO  ==> Generating etcd config file using env variables
etcd 10:25:22.70 INFO  ==> 
etcd 10:25:22.71 INFO  ==> get_etcd_active_endpoints: 
etcd 10:25:22.72 INFO  ==> There is no data from previous deployments
etcd 10:25:22.73 INFO  ==> Adding new member to existing cluster
etcd 10:25:22.73 ERROR ==> No active endpoints in cluster, wait 10s, and restart the pod
```
Can anyone help
