### ISSUE TITLE
Setting Milvus log level config is not working

### ISSUE THREAD

**Issue by YGao119** [zilliztech/milvus-operator#335]
I am trying to set milvus log level to "warn"+ (since the proxy node is logging too much in production), but all the config for log level doesn't seem to be working.  I wonder if there is other way to set the log level correctly or if I am missing something here.

Also, It will be great to know how to set log level for individual component and dependency. 

Tried both below.
```
...
spec:
  mode: cluster

  config:
    log:
      level: warn
  ...
```

```
...
spec:
  mode: cluster

  config:
    milvus:
      log:
        level: warn
  ...
```
