### ISSUE TITLE
query Node is not updating after changing the image version

### ISSUE THREAD

**Issue by YGao119** [zilliztech/milvus-operator#342]
CRD

```
spec:
  mode: cluster

  components:
    enableRollingUpdate: false
    image: milvusdb/milvus:v2.5.12-gpu # Milvus image with gpu support
    imageUpdateMode: all
```

I am upgrading the Milvus version from 2.5.10 to 2.5.12, even though all the other components are able to update, the query-nodes (0 and 1) are stuck with the old version. I wonder if this is a known issue.
