### ISSUE TITLE
storageclass 'local-path' not assigned leading to pvc unbound to tainted nodes

### ISSUE THREAD

**Issue by John1Tang** [zilliztech/milvus-operator#357]
Error:

```
k get po -n serviceteam -o wide| grep my-release
my-release-etcd-0                                  0/1     CrashLoopBackOff   14         57m     10.244.14.243   aa2            <none>           <none>
my-release-etcd-1                                  0/1     CrashLoopBackOff   14         57m     10.244.19.168   aa1   <none>           <none>
my-release-etcd-2                                  0/1     CrashLoopBackOff   14         57m     10.244.14.244  aa2            <none>           <none>
my-release-pulsar-bookie-0                         0/1     Pending            0          58m     <none>          <none>                          <none>           <none>
my-release-pulsar-bookie-1                         0/1     Pending            0          58m     <none>          <none>                          <none>           <none>
my-release-pulsar-bookie-2                         0/1     Pending            0          58m     <none>          <none>                          <none>           <none>
my-release-pulsar-broker-0                         0/1     Init:0/2           0          58m     10.244.14.239   aa1            <none>           <none>
my-release-pulsar-broker-1                         0/1     Init:0/2           0          58m     10.244.19.165   aa2   <none>           <none>
my-release-pulsar-proxy-0                          0/1     Init:0/2           0          58m     10.244.14.240  aa1           <none>           <none>
my-release-pulsar-proxy-1                          0/1     Init:0/2           0          58m     10.244.19.166   aa1   <none>           <none>
my-release-pulsar-recovery-0                       0/1     Init:0/1           0          58m     10.244.9.84     e1       <none>           <none>
my-release-pulsar-zookeeper-0                      0/1     Pending            0          58m     <none>          <none>                          <none>           <none>
my-release-pulsar-zookeeper-1                      0/1     Pending            0          58m     <none>          <none>                          <none>           <none>
my-release-pulsar-zookeeper-2                      0/1     Pending            0          58m     <none>          <none>                          <none>           <none>
```
noted node e1 is not one of tainted nodes

### Environment:
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:41:22Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.10", GitCommit:"a7a32748b5c60445c4c7ee904caf01b91f2dbb71", GitTreeState:"clean", BuildDate:"2022-02-16T11:18:16Z", GoVersion:"go1.16.14", Compiler:"gc", Platform:"linux/amd64"}
```

my config to apply:

```
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: my-release
  labels:
    app: milvus
spec:
  mode: cluster
  components:
    # Global nodeSelector and tolerations for Milvus components
    nodeSelector:
      role: serviceteam
    tolerations:
      - key: "role"
        operator: "Equal"
        value: "serviceteam"
        effect: "NoSchedule"

    mixCoord:
      replicas: 1
      resources:
        limits:
          cpu: 8
          memory: 32Gi

    indexNode:
      replicas: 8
      resources:
        limits:
          cpu: 8
          memory: 16Gi

    proxy:
      replicas: 1
      resources:
        limits:
          cpu: 8
          memory: 32Gi

    queryNode:
      replicas: 6
      resources:
        limits:
          cpu: 8
          memory: 32Gi

    dataNode:
      replicas: 1
      resources:
        limits:
          cpu: 8
          memory: 32Gi

  dependencies:
    etcd:
      inCluster:
        values:
          # Global settings for etcd
          global:
            nodeSelector:
              role: serviceteam
            tolerations:
              - key: "role"
                operator: "Equal"
                value: "serviceteam"
                effect: "NoSchedule"

          replicaCount: 3
          autoCompactionMode: revision
          autoCompactionRetention: "1000"

          # Apply to etcd pods specifically
          nodeSelector:
            role: serviceteam
          tolerations:
            - key: "role"
              operator: "Equal"
              value: "serviceteam"
              effect: "NoSchedule"

          extraEnvVars:
            - name: ETCD_QUOTA_BACKEND_BYTES
              value: "4294967296"

          persistence:
            enabled: true
            storageClass: "local-path"
            size: 20Gi

          resources:
            limits:
              cpu: 1
              memory: 4Gi

    pulsar:
      inCluster:
        values:
          # Global settings for all Pulsar components
          global:
            nodeSelector:
              role: serviceteam
            tolerations:
              - key: "role"
                operator: "Equal"
                value: "serviceteam"
                effect: "NoSchedule"

          # Individual component overrides
          recovery:
            replicaCount: 1
            nodeSelector:
              role: serviceteam
            tolerations:
              - key: "role"
                operator: "Equal"
                value: "serviceteam"
                effect: "NoSchedule"
          proxy:
            replicaCount: 2
            nodeSelector:
              role: serviceteam
            tolerations:
              - key: "role"
                operator: "Equal"
                value: "serviceteam"
                effect: "NoSchedule"

          zookeeper:
            replicaCount: 3
            nodeSelector:
              role: serviceteam
            tolerations:
              - key: "role"
                operator: "Equal"
                value: "serviceteam"
                effect: "NoSchedule"
            persistence:
              enabled: true
              storageClass: "local-path"
              size: 30Gi

          bookkeeper:
            replicaCount: 3
            nodeSelector:
              role: serviceteam
            tolerations:
              - key: "role"
                operator: "Equal"
                value: "serviceteam"
                effect: "NoSchedule"
            persistence:
              journal:
                storageClass: "local-path"
                size: 50Gi
              ledgers:
                storageClass: "local-path"
                size: 161Gi

          broker:
            replicaCount: 2
            nodeSelector:
              role: serviceteam
            tolerations:
              - key: "role"
                operator: "Equal"
                value: "serviceteam"
                effect: "NoSchedule"

    storage:
      inCluster:
        values:
          mode: distributed

          # Global settings for MinIO
          nodeSelector:
            role: serviceteam
          tolerations:
            - key: "role"
              operator: "Equal"
              value: "serviceteam"
              effect: "NoSchedule"

          persistence:
            enabled: true
            storageClass: "local-path"
            size: 347Gi

          resources:
            limits:
              cpu: 1
              memory: 8Gi
```

check on pvc created

```
k get pvc data-my-release-etcd-0  -o yaml -n serviceteam
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
    volume.kubernetes.io/selected-node: as16.austria.private
  creationTimestamp: "2025-06-13T06:25:04Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/instance: my-release-etcd
    app.kubernetes.io/name: etcd
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:volume.kubernetes.io/selected-node: {}
    manager: kube-scheduler
    operation: Update
    time: "2025-06-13T06:25:04Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:pv.kubernetes.io/bind-completed: {}
          f:pv.kubernetes.io/bound-by-controller: {}
          f:volume.beta.kubernetes.io/storage-provisioner: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/name: {}
      f:spec:
        f:accessModes: {}
        f:resources:
          f:requests:
            .: {}
            f:storage: {}
        f:storageClassName: {}
        f:volumeMode: {}
        f:volumeName: {}
      f:status:
        f:accessModes: {}
        f:capacity:
          .: {}
          f:storage: {}
        f:phase: {}
    manager: kube-controller-manager
    operation: Update
    time: "2025-06-13T06:25:06Z"
  name: data-my-release-etcd-0
  namespace: serviceteam
  resourceVersion: "727999258"
  uid: e2ccdac4-29cc-485b-a825-f1485c193011
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: pvc-e2ccdac4-29cc-485b-a825-f1485c193011
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  phase: Bound


k get pvc my-release-pulsar-bookie-journal-my-release-pulsar-bookie-0 -o yaml -n serviceteam
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: "2025-06-13T06:24:41Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: pulsar
    component: bookie
    release: my-release-pulsar
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
          f:component: {}
          f:release: {}
      f:spec:
        f:accessModes: {}
        f:resources:
          f:requests:
            .: {}
            f:storage: {}
        f:volumeMode: {}
    manager: kube-controller-manager
    operation: Update
    time: "2025-06-13T06:24:41Z"
  name: my-release-pulsar-bookie-journal-my-release-pulsar-bookie-0
  namespace: serviceteam
  resourceVersion: "727998689"
  uid: 0cc6fcce-b45b-48e3-8826-4bdd31e9e3d7
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem
status:
  phase: Pending
```

**Comment by John1Tang** [comment]
@haorenfsa did use `k get events -n xx` and it was like 
```
29m         Normal    FailedBinding      persistentvolumeclaim/my-release-pulsar-bookie-journal-my-release-pulsar-bookie-0      no persistent volumes available for this claim and no storage class is set

 k describe pvc my-release-pulsar-bookie-journal-my-release-pulsar-bookie-0 -n serviceteam
Name:          my-release-pulsar-bookie-journal-my-release-pulsar-bookie-0
Namespace:     serviceteam
StorageClass:  
Status:        Pending
Volume:        
Labels:        app=pulsar
               component=bookie
               release=my-release-pulsar
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Mounted By:    my-release-pulsar-bookie-0
Events:
  Type    Reason         Age                   From                         Message
  ----    ------         ----                  ----                         -------
  Normal  FailedBinding  26s (x4543 over 18h)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
...
```

**Comment by John1Tang** [comment]
I've changed my yaml, now pulsar components not bound to local-path
```
k get pvc -n serviceteam -o wide
NAME                                                             STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE    VOLUMEMODE
data-my-release-etcd-0                                           Bound     pvc-bcc385e7-79e9-4e45-a5fa-65de62bdfa2d   20Gi       RWO            local-path     119m   Filesystem
data-my-release-etcd-1                                           Bound     pvc-edc4cd49-194c-4fac-b795-6568759b6bed   20Gi       RWO            local-path     119m   Filesystem
data-my-release-etcd-2                                           Bound     pvc-9df65851-f535-4d5b-b5f0-a934727c427b   20Gi       RWO            local-path     119m   Filesystem
export-my-release-minio-0                                        Bound     pvc-e895f841-6196-43d3-9c26-c74af4d54409   347Gi      RWO            local-path     119m   Filesystem
export-my-release-minio-1                                        Bound     pvc-fd20ee25-fb92-4ad6-893a-eb963cd5d061   347Gi      RWO            local-path     119m   Filesystem
export-my-release-minio-2                                        Bound     pvc-f068cab6-906d-430d-be8f-f9960f3f1595   347Gi      RWO            local-path     119m   Filesystem
export-my-release-minio-3                                        Bound     pvc-2523c136-f983-43bc-a596-445f2b58587f   347Gi      RWO            local-path     119m   Filesystem
local-path-pvc                                                   Bound     pvc-29284666-c7fc-4360-8e48-53422922bafa   128Mi      RWO            local-path     6d1h   Filesystem
my-release-pulsar-bookie-journal-my-release-pulsar-bookie-0      Pending                                                                                       119m   Filesystem
my-release-pulsar-bookie-journal-my-release-pulsar-bookie-1      Pending                                                                                       119m   Filesystem
my-release-pulsar-bookie-journal-my-release-pulsar-bookie-2      Pending                                                                                       119m   Filesystem
my-release-pulsar-bookie-ledgers-my-release-pulsar-bookie-0      Pending                                                                                       119m   Filesystem
my-release-pulsar-bookie-ledgers-my-release-pulsar-bookie-1      Pending                                                                                       119m   Filesystem
my-release-pulsar-bookie-ledgers-my-release-pulsar-bookie-2      Pending                                                                                       119m   Filesystem
my-release-pulsar-zookeeper-data-my-release-pulsar-zookeeper-0   Pending                                                                                       119m   Filesystem
my-release-pulsar-zookeeper-data-my-release-pulsar-zookeeper-1   Pending                                                                                       119m   Filesystem
my-release-pulsar-zookeeper-data-my-release-pulsar-zookeeper-2   Pending                                                                                       119m   Filesystem

```

my operatorConfigYml.yml
```
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: my-release
  labels:
    app: milvus
spec:
  mode: cluster
  components:
    # Global nodeSelector and tolerations for Milvus components
    nodeSelector:
      role: serviceteam
    tolerations:
      - key: "role"
        operator: "Equal"
        value: "serviceteam"
        effect: "NoSchedule"

    mixCoord:
      replicas: 1
      resources:
        limits:
          cpu: 8
          memory: 32Gi

    indexNode:
      replicas: 8
      resources:
        limits:
          cpu: 8
          memory: 16Gi

    proxy:
      replicas: 1
      resources:
        limits:
          cpu: 8
          memory: 32Gi

    queryNode:
      replicas: 6
      resources:
        limits:
          cpu: 8
          memory: 32Gi

    dataNode:
      replicas: 1
      resources:
        limits:
          cpu: 8
          memory: 32Gi

  dependencies:
    etcd:
      inCluster:
        values:
          # Global settings for etcd
          global:
            nodeSelector:
              role: serviceteam
            tolerations:
              - key: "role"
                operator: "Equal"
                value: "serviceteam"
                effect: "NoSchedule"

          replicaCount: 3
          autoCompactionMode: revision
          autoCompactionRetention: "1000"

          # Apply to etcd pods specifically
          nodeSelector:
            role: serviceteam
          tolerations:
            - key: "role"
              operator: "Equal"
              value: "serviceteam"
              effect: "NoSchedule"

          extraEnvVars:
            - name: ETCD_QUOTA_BACKEND_BYTES
              value: "4294967296"
            - name: ETCD_HEARTBEAT_INTERVAL
              value: "500"
            - name: ETCD_ELECTION_TIMEOUT
              value: "25000"
            - name: ETCD_SNAPSHOT_COUNT
              value: "10000"
            - name: ETCD_ENABLE_PPROF
              value: "true"

          persistence:
            enabled: true
            storageClass: "local-path"
#            storageClassName: "local-path"
            size: 20Gi

          resources:
            limits:
              cpu: 1
              memory: 4Gi

    pulsar:
      inCluster:
        values:
#          default_storage:
#            existingStorageClassName: local-path
#            size: 100Mi
          # Global settings for all Pulsar components
          global:
            nodeSelector:
              role: serviceteam
            tolerations:
              - key: "role"
                operator: "Equal"
                value: "serviceteam"
                effect: "NoSchedule"

          # Individual component overrides
          recovery:
            replicaCount: 1
            nodeSelector:
              role: serviceteam
            tolerations:
              - key: "role"
                operator: "Equal"
                value: "serviceteam"
                effect: "NoSchedule"
          proxy:
            replicaCount: 2
            nodeSelector:
              role: serviceteam
            tolerations:
              - key: "role"
                operator: "Equal"
                value: "serviceteam"
                effect: "NoSchedule"

          zookeeper:
            replicaCount: 3
            nodeSelector:
              role: serviceteam
            tolerations:
              - key: "role"
                operator: "Equal"
                value: "serviceteam"
                effect: "NoSchedule"
            volumes:
              persistence: true
              data:
                name: data
                size: 30Gi   #SSD Required
                storageClassName: local-path

          bookkeeper:
            replicaCount: 3
            nodeSelector:
              role: serviceteam
            tolerations:
              - key: "role"
                operator: "Equal"
                value: "serviceteam"
                effect: "NoSchedule"
            volumes:
              journal:
                name: journal
                size: 50Gi
                storageClassName: local-path
              ledgers:
                name: ledgers
                size: 161Gi   #SSD Required
                storageClassName: local-path

          broker:
            replicaCount: 2
            nodeSelector:
              role: serviceteam
            tolerations:
              - key: "role"
                operator: "Equal"
                value: "serviceteam"
                effect: "NoSchedule"

    storage:
      inCluster:
        values:
          mode: distributed

          # Global settings for MinIO
          nodeSelector:
            role: serviceteam
          tolerations:
            - key: "role"
              operator: "Equal"
              value: "serviceteam"
              effect: "NoSchedule"

          persistence:
            enabled: true
            storageClass: "local-path"
#            storageClassName: "local-path"
            size: 347Gi
            pvcDeletion: true
            persistentVolumeClaim:
              spec:
                accessModes: [ "ReadWriteOnce" ]
                storageClassName: "local-path"
                resources:
                  requests:
                    storage: 347Gi


          resources:
            limits:
              cpu: 1
              memory: 8Gi
```
any ideas? @haorenfsa @rehevkor5
