### ISSUE TITLE
Can we use a custom storageclass for pulsar?

### ISSUE THREAD

**Issue by yuzs2** [zilliztech/milvus-operator#45]
Hi, I'm trying to create a milvus cluster via milvus-operator in a private environment. In our environment, we must specify the storageClassName for each PVC.

For etcd and minio, I found it's easy to specify the storageclass like the below:
```
spec:
  mode: cluster
  dependencies: 
    etcd:
      inCluster:
        values:
          image:
            repository: harbor-repo.vmware.com/dockerhub-proxy-cache/milvusdb/etcd
            tag: 3.5.5-r2
          persistence:
            storageClass: e2536828f9fd4faaa2df59f96db45d13
            size: 100Mi
    storage:
        inCluster:
          values: 
            #image: harbor-repo.vmware.com/dockerhub-proxy-cache/minio/minio:RELEASE.2023-03-20T20-16-18Z 
            image:
              repository: harbor-repo.vmware.com/dockerhub-proxy-cache/minio/minio
              tag: RELEASE.2023-03-20T20-16-18Z
            persistence:
              storageClass: e2536828f9fd4faaa2df59f96db45d13
              size: 100Mi
```

But for pulsar, it's really not easy to find the correct way for the configuration. Now all my PVCs for pulsar are stunk in pending due to no storageclass being set. 
```
NAME                                                                                   STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                       AGE
persistentvolumeclaim/data-yu-release-etcd-0                                           Bound     pvc-32349b7b-d478-47a1-a221-8abef068f61e   100Mi      RWO            e2536828f9fd4faaa2df59f96db45d13   94m
......
persistentvolumeclaim/yu-release-pulsar-bookie-journal-yu-release-pulsar-bookie-0      Pending                                                                                                           24m
persistentvolumeclaim/yu-release-pulsar-bookie-ledgers-yu-release-pulsar-bookie-0      Pending                                                                                                           24m
persistentvolumeclaim/yu-release-pulsar-zookeeper-data-yu-release-pulsar-zookeeper-0   Pending                                                                                                           24m
```

```
 ➭ kubectl describe pvc yu-release-pulsar-bookie-journal-yu-release-pulsar-bookie-0
Name:          yu-release-pulsar-bookie-journal-yu-release-pulsar-bookie-0
Namespace:     libra-yu-test
StorageClass:  
Status:        Pending
Volume:        
Labels:        app=pulsar
               component=bookie
               release=yu-release-pulsar
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Mounted By:    <none>
Events:
  Type    Reason         Age                  From                         Message
  ----    ------         ----                 ----                         -------
  Normal  FailedBinding  34s (x102 over 25m)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
```

The below configuration just does not work:
```
spec:
  mode: cluster
  dependencies: 
    pulsar:
          inCluster:
            values:
              persistence:
                storageClass: e2536828f9fd4faaa2df59f96db45d13
                size: 100Mi
```

How can I fix this? Could you please help? Thanks!

**Comment by haorenfsa** [comment]
@yuzs2  You can find fields detailed description in this doc: https://github.com/zilliztech/milvus-operator/blob/main/docs/CRD/milvus.md, according to which, a complete set of pulsar chart values can be found here: https://github.com/kafkaesque-io/pulsar-helm-chart/blob/pulsar-1.0.31/helm-chart-sources/pulsar/values.yaml.

You'll find the value field for pulsar is `default_storage.existingStorageClassName`.

**Comment by haorenfsa** [comment]
- [ ] Add a `sample.yaml` with a complete set of all configuration fields in Milvus CR

**Comment by yuzs2** [comment]
@haorenfsa Thanks for the quick reply. I added the `spec. dependencies.pulsar.inCluster.values.default_storage.existingStorageClassName` but seems it does not work. 
Also, as 2 of the pending PVCs are related to bookkeeper, I added the `existingStorageClassName` for `spec. dependencies.pulsar.inCluster.values.bookkeeper.volume.journal.existingStorageClassName` but it does not work either, with the same error as before.

```
# https://raw.githubusercontent.com/zilliztech/milvus-operator/main/config/samples/milvus_cluster_default.yaml

# This is a sample to deploy a milvus cluster in milvus-operator's default configurations.
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: yu-release
  namespace: libra-yu-test
  labels:
    app: milvus
spec:
  mode: cluster
  dependencies: 
    etcd:
      inCluster:
        values:
          #image: harbor-repo.vmware.com/dockerhub-proxy-cache/milvusdb/etcd:3.5.5-r2
          image:
            repository: harbor-repo.vmware.com/dockerhub-proxy-cache/milvusdb/etcd
            tag: 3.5.5-r2
          persistence:
            storageClass: e2536828f9fd4faaa2df59f96db45d13
            size: 100Mi
            # annotations: 
            #   volume.beta.kubernetes.io/storage-provisioner: csi.vsphere.vmware.com
          resources:
            limits:
              cpu: '200m'
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 512Mi
    pulsar:
      inCluster:
        values:
          default_storage:
            existingStorageClassName: e2536828f9fd4faaa2df59f96db45d13
            size: 100Mi
          autorecovery:
            resources:
              limits:
                cpu: '200m'
                memory: 512Mi
              requests:
                cpu: 200m
                memory: 512Mi 
          bookkeeper:
            resources:
              limits:
                cpu: '200m'
                memory: 512Mi
              requests:
                cpu: 200m
                memory: 512Mi
            volumes:
              journal:
                name:  journal
                size:  100Mi
                existingStorageClassName: e2536828f9fd4faaa2df59f96db45d13
              ledgers:
                name:  ledgers
                size:  200Mi
                existingStorageClassName: e2536828f9fd4faaa2df59f96db45d13
          broker:
            resources:
              limits:
                cpu: '200m'
                memory: 512Mi
              requests:
                cpu: 200m
                memory: 512Mi
          images:
            autorecovery:
              repository:   harbor-repo.vmware.com/dockerhub-proxy-cache/apachepulsar/pulsar
              rag:          2.8.2
            bookie:
              repository:   harbor-repo.vmware.com/dockerhub-proxy-cache/apachepulsar/pulsar
              rag:          2.8.2
            broker:
              repository:   harbor-repo.vmware.com/dockerhub-proxy-cache/apachepulsar/pulsar
              rag:          2.8.2
            proxy:
              repository:   harbor-repo.vmware.com/dockerhub-proxy-cache/apachepulsar/pulsar
              rag:          2.8.2
            pulsar_manager:
              repository:   harbor-repo.vmware.com/dockerhub-proxy-cache/apachepulsar/pulsar-manager
              rag:          v0.1.0
            zookeeper:
              repository:   harbor-repo.vmware.com/dockerhub-proxy-cache/apachepulsar/pulsar
              rag:          2.8.2
          proxy:
            resources:
              limits:
                cpu: '200m'
                memory: 512Mi
              requests:
                cpu: 200m
                memory: 512Mi
          pulsar_metadata:
            repository:   harbor-repo.vmware.com/dockerhub-proxy-cache/apachepulsar/pulsar
            rag:          2.8.2
          zookeeper:
            resources:
              limits:
                cpu: '200m'
                memory: 512Mi
              requests:
                cpu: 200m
                memory: 512Mi
    rocksmq:
      persistence:
        persistentVolumeClaim:
          spec:
            storageClassName: e2536828f9fd4faaa2df59f96db45d13
            size: 100Mi
    storage:
      inCluster:
        values: 
          #image: harbor-repo.vmware.com/dockerhub-proxy-cache/minio/minio:RELEASE.2023-03-20T20-16-18Z 
          image:
            repository: harbor-repo.vmware.com/dockerhub-proxy-cache/minio/minio
            tag: RELEASE.2023-03-20T20-16-18Z
          persistence:
            storageClass: e2536828f9fd4faaa2df59f96db45d13
            size: 100Mi
            # annotations: 
            #   volume.beta.kubernetes.io/storage-provisioner: csi.vsphere.vmware.com
          resources:
            limits:
              cpu: '200m'
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 512Mi
  components:
    image: harbor-repo.vmware.com/dockerhub-proxy-cache/milvusdb/milvus:v2.3.2
    resources:
      limits:
        cpu: '200m'
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 512Mi
  config: {}
```


Am I missing any extra steps? Please kindly advise. Thanks!

**Comment by haorenfsa** [comment]
@yuzs2 Sry. I checked the [value doc](https://github.com/kafkaesque-io/pulsar-helm-chart/blob/pulsar-1.0.31/helm-chart-sources/pulsar/values.yaml) again, and found is out of date.  

What milvus-operator is currently using is close to this https://artifacthub.io/packages/helm/apache/pulsar?modal=values

for example under `spec.dependencies.pulsar.inCluster.values`, set:
```yaml
zookeeper:
  volumes:
    data:
      storageClassName: e2536828f9fd4faaa2df59f96db45d13
      size: 100Mi
bookkeeper:
  volumes:
    journal:
      storageClassName: e2536828f9fd4faaa2df59f96db45d13
      size: 100Mi
    ledgers:
      storageClassName: e2536828f9fd4faaa2df59f96db45d13
      size: 100Mi
```
