### ISSUE TITLE
Is there a way to disable the checker job?

### ISSUE THREAD

**Issue by webcoderz** [zilliztech/milvus-operator#47]
I am running milvus operator on argoCD and there is an job that happens frequently that keeps the operator in a "Progressing" state, and after it runs it goes into a degraded state despite working fine, it seems to be due to the checker job, is there a way to disable it?

**Comment by haorenfsa** [comment]
No for now. We'll add an option soon.

**Comment by adam-huganir** [comment]
> I am running milvus operator on argoCD and there is an job that happens frequently that keeps the operator in a "Progressing" state, and after it runs it goes into a degraded state despite working fine, it seems to be due to the checker job, is there a way to disable it?

It's been a while so it's unlikely this is still blocking you, but if anyone else comes across this you can specify that it is a job in argo with argo-specific annotation for jobs by adding it in the values file and it will succeed:

```yaml
checker:
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
```
