### ISSUE TITLE
Coordinator HA

### ISSUE THREAD

**Issue by taptao** [zilliztech/milvus-operator#53]
Is coordinator HA configuration now supported?

See from https://milvus.io/docs/coordinator_ha.md#Coordinator-HA that helm supports activeStandby parameter setting Coordinator component in active and standby mode.

Does milvus-operator support active and standby modes?

**Comment by haorenfsa** [comment]
Yes it supports, but not directly for now. you need to set the `spec.config` field like below. We will add a field to make it more easily later.

```yaml
spec:
  config:
    rootCoord:
      enableActiveStandby: true
    dataCoord:
      enableActiveStandby: true
    queryCoord:
      enableActiveStandby: true
    indexCoord:
      enableActiveStandby: true
```
