### ISSUE TITLE
Support for custom storage limits with the Minio deployment in operator

### ISSUE THREAD

**Issue by Tanchwa** [zilliztech/milvus-operator#54]
Hello, is there a way to specify how much storage is requested by the PVCs for Minio? I'm trying to do a POC deployment on my homelab and 500Gib per instance is WAY more than I can afford to spare.

I checked the values files on the chart as well as the cluster configuration options and the docs on the storage component and didn't find anything, so if it already exists, and if I'm just missing where to configure it, let me know.

**Comment by haorenfsa** [comment]
@Tanchwa  It seems you put the size field in the wrong place. I tested it my self and it works fine. below is my full CR:

```yaml
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: my-release
  labels:
    app: milvus
spec:
  config: {}
  components:
    standalone:
      replicas: 1
      serviceType: LoadBalancer
  dependencies:
    etcd:
      inCluster:
        values:
          replicaCount: 1
        deletionPolicy: Delete
        pvcDeletion: true
    storage:
      inCluster:
        values:
          mode: standalone
          resources:
            requests:
              memory: 100Mi
          persistence:
            size: 20Gi
        deletionPolicy: Delete
        pvcDeletion: true
```

**Comment by Tanchwa** [comment]
Nope, that's where I have it, too.

```
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: my-release
  labels:
    app: milvus
spec:
  mode: cluster
  dependencies:
    etcd:
      inCluster:
        values:
          replicaCount: 1
    pulsar:
      inCluster:
        values:
          components:
            autorecovery: false
            functions: false
            toolset: false
            pulsar_manager: false
          monitoring:
            prometheus: false
            grafana: false
            node_exporter: false
            alert_manager: false
          proxy:
            replicaCount: 1
            resources:
              requests:
                cpu: 0.01
                memory: 256Mi
            configData:
              PULSAR_MEM: >
                -Xms256m -Xmx256m
              PULSAR_GC: >
                -XX:MaxDirectMemorySize=256m
          bookkeeper:
            replicaCount: 2
            resources:
              requests:
                cpu: 0.01
                memory: 256Mi
            configData:
              PULSAR_MEM: >
                -Xms256m
                -Xmx256m
                -XX:MaxDirectMemorySize=256m
              PULSAR_GC: >
                -Dio.netty.leakDetectionLevel=disabled
                -Dio.netty.recycler.linkCapacity=1024
                -XX:+UseG1GC -XX:MaxGCPauseMillis=10
                -XX:+ParallelRefProcEnabled
                -XX:+UnlockExperimentalVMOptions
                -XX:+DoEscapeAnalysis
                -XX:ParallelGCThreads=32
                -XX:ConcGCThreads=32
                -XX:G1NewSizePercent=50
                -XX:+DisableExplicitGC
                -XX:-ResizePLAB
                -XX:+ExitOnOutOfMemoryError
                -XX:+PerfDisableSharedMem
                -XX:+PrintGCDetails
          zookeeper:
            replicaCount: 1
            resources:
              requests:
                cpu: 0.01
                memory: 256Mi
            configData:
              PULSAR_MEM: >
                -Xms256m
                -Xmx256m
              PULSAR_GC: >
                -Dcom.sun.management.jmxremote
                -Djute.maxbuffer=10485760
                -XX:+ParallelRefProcEnabled
                -XX:+UnlockExperimentalVMOptions
                -XX:+DoEscapeAnalysis -XX:+DisableExplicitGC
                -XX:+PerfDisableSharedMem
                -Dzookeeper.forceSync=no
          broker:
            replicaCount: 1
            resources:
              requests:
                cpu: 0.01
                memory: 256Mi
            configData:
              PULSAR_MEM: >
                -Xms256m
                -Xmx256m
              PULSAR_GC: >
                -XX:MaxDirectMemorySize=256m
                -Dio.netty.leakDetectionLevel=disabled
                -Dio.netty.recycler.linkCapacity=1024
                -XX:+ParallelRefProcEnabled
                -XX:+UnlockExperimentalVMOptions
                -XX:+DoEscapeAnalysis
                -XX:ParallelGCThreads=32
                -XX:ConcGCThreads=32
                -XX:G1NewSizePercent=50
                -XX:+DisableExplicitGC
                -XX:-ResizePLAB
                -XX:+ExitOnOutOfMemoryError
    storage:
      inCluster:
        values:
          mode: standalone
          persistance:
            size: 20Gi
```

**Comment by haorenfsa** [comment]
@Tanchwa Then it's because you didn't delete the PVC before you redeploy. By default milvus-operator won't delete the depencencies & data when you delete Milvus CR.  

The minio release & data is only deleted when you specify Milvus CR like below.
```yaml 
spec:
  dependencies:
    storage:
      inCluster:
        deletionPolicy: Delete
        pvcDeletion: true
```

So here is how to fix this, you should add the `deletionPolicy` & `pvcDeletion` values to apply you milvus CR again, and then delete it, and wait for the PVCs to be cleaned, and then create the Milvus CR once more.

**Comment by Tanchwa** [comment]
I already said that I had deleted them and restarted. Do you try another reason why it could not be working?

**Comment by haorenfsa** [comment]
@Tanchwa I'm quite sure about the reason, did you set your CR like below before you delete it ?
```yaml
spec:
  dependencies:
    storage:
      inCluster:
        deletionPolicy: Delete
        pvcDeletion: true
```

If not, use `helm list` & `kubectl get pvc` to check the left behind things in your kubernetes.

Use `helm uninstall xxx` & `kubectl delete pvc xxx` to clean them up.
