### ISSUE TITLE
Failed to create resource due to perms cluster-pulsar

### ISSUE THREAD

**Issue by webcoderz** [zilliztech/milvus-operator#61]
controller.helm	warning: Upgrade "cluster-pulsar" failed: failed to create resource: clusterroles.rbac.authorization.k8s.io "cluster-pulsar-prometheus" is forbidden: user "system:serviceaccount:milvus-cluster-operator:milvus-operator" (groups=["system:serviceaccounts" "system:serviceaccounts:milvus-cluster-operator" "system:authenticated"]) is attempting to grant RBAC permissions not currently held:
{APIGroups:[""], Resources:["endpoints"], Verbs:["get" "list" "watch"]}
{APIGroups:[""], Resources:["nodes"], Verbs:["get" "list" "watch"]}
{APIGroups:[""], Resources:["nodes/proxy"], Verbs:["get" "list" "watch"]}
{NonResourceURLs:["/metrics"], Verbs:["get"]}

When trying to install the Milvus cluster

**Comment by webcoderz** [comment]
Fixed with this


```

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: milvus-operator-additional
rules:
- apiGroups: [""]
  resources: ["endpoints", "nodes", "nodes/proxy"]
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: milvus-operator-additional-binding
subjects:
- kind: ServiceAccount
  name: milvus-operator
  namespace: milvus-cluster-operator
roleRef:
  kind: ClusterRole
  name: milvus-operator-additional
  apiGroup: rbac.authorization.k8s.io

```
