### ISSUE TITLE
Milvus Operator confusion

### ISSUE THREAD

**Issue by mxchinegod** [zilliztech/milvus-operator#89]
Hello. Some questions.

When using the Operator and installing a Milvus cluster with kubectl apply -f like so

```yaml
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: wtf
  namespace: workspace
  labels:
    app: milvus
spec:
  config: {}
```

the cluster creates but no service on 19530 is created. Additionally I just see minio and etc. 

furthermore deleting does not do anything to the CRD object (Milvus)

<img width="677" alt="Screenshot 2024-03-06 at 8 58 04 PM" src="https://github.com/zilliztech/milvus-operator/assets/12659763/4892d49a-cdd6-40e4-9f20-87b80c85eff9">

What does the Operator do so I can be sure to use it correctly? 

Each time I have had to delete resources manually and it seems like they will not deploy again using the same name... 

**ATTENTIONS: THE MAIN BRANCH MAY BE IN AN UNSTABLE OR EVEN BROKEN STATE DURING DEVELOPMENT.**
Which branch should we use?

**Comment by mxchinegod** [comment]
Merely using the operator as a sub chart:

❯ helm install milvus . 
NAME: milvus
LAST DEPLOYED: Wed Mar  6 21:08:19 2024
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None

helm-charts.git/milvus on  main [!?] is 📦 v1.0.0 via ⎈ v3.12.3 on ☁️  (us-east-1) took 2s 
❯ kubectl apply -f ./templates/*
Error from server (InternalError): error when creating "./templates/test-cluster.yaml": Internal error occurred: failed calling webhook "mmilvus.kb.io": failed to call webhook: Post "https://milvus-milvus-operator-webhook-service.default.svc:443/mutate-milvus-io-v1beta1-milvus?timeout=10s": no endpoints available for service "milvus-milvus-operator-webhook-service"

**Comment by haorenfsa** [comment]
Hi @mxchinegod, 
1. the formal released charts can be found in
https://github.com/zilliztech/milvus-operator/releases

or through our chart repo: `helm repo add milvus-operator https://zilliztech.github.io/milvus-operator/`

for more info, check the docs in repo: https://github.com/zilliztech/milvus-operator/blob/main/docs/installation/installation.md


2. kubectl apply -f ./templates/*
> Error from server (InternalError): error when creating "./templates/test-cluster.yaml": Internal error occurred: failed calling webhook "mmilvus.kb.io": failed to call webhook: Post "https://milvus-milvus-operator-webhook-service.default.svc:443/mutate-milvus-io-v1beta1-milvus?timeout=10s": no endpoints available for service "milvus-milvus-operator-webhook-service"

This is because your milvus-operator is still being installed, try use `--wait` in your `helm install` command
<img width="1637" alt="image" src="https://github.com/zilliztech/milvus-operator/assets/15938850/1e38a6b0-41ca-4b6e-9e04-7de993df40cb">




3. About dependency auto deletion

By default all dependency and data are kept when you delete the CR, so that you can still recover your milvus & data through  creating a CR of the same name.

If you want to delete one of the dependency & data as well, take pulsar as example:

```yaml 
spec:
  dependencies: 
    pulsar:
      inCluster: 
        deletionPolicy: Delete
        pvcDeletion: true
```

Same changes should be applied to all your dependencies :
```
spec:
  dependencies: 
    pulsar:
      inCluster: 
        deletionPolicy: Delete
        pvcDeletion: true
    etcd:
      inCluster: 
        deletionPolicy: Delete
        pvcDeletion: true
    storage:
      inCluster: 
        deletionPolicy: Delete
        pvcDeletion: true
```
